Панин Максим 3HW
czertyaka/CppDevCourse-hw3 pull request #13
Opened 2024-12-01 16:13 UTC by PaninMaxim

2024-12-08 11:33 UTC, czertyaka requested changes

2024-12-08 11:33 UTC, czertyaka commented on src/two-sum.cpp
> +#define ARRAY_SIZE 5
Можно подключить заголовочный файл two-sum.hpp и не дублировать определение макроса

2024-12-08 11:33 UTC, czertyaka commented on src/two-sum.cpp
> +#include <iostream>
Заголовочный файл не используется

2024-12-08 11:33 UTC, czertyaka commented on src/two-sum.cpp
> +	unsigned int kolvo_par = 0;
Зачем считаете количество пар? По условию задачи подойдет любая пара

2024-12-08 11:33 UTC, czertyaka commented on src/two-sum.cpp
> +		for (unsigned int j = i + 1; j <= ARRAY_SIZE; j++)
Условие должно быть `< ARRAY_SIZE`. Сейчас имеем выход за границы массива, что показывают [тесты](https://github.com/czertyaka/CppDevCourse-hw3/actions/runs/12107085066/job/34090372814?pr=13)

2024-12-15 18:50 UTC, czertyaka requested changes

2024-12-15 18:50 UTC, czertyaka commented on src/two-sum.cpp
> +		for (unsigned int j = i + 1; j <= ARRAY_SIZE; j++)
В этой строке все еще условие неверно

2024-12-17 17:15 UTC, PaninMaxim commented on src/two-sum.cpp
> +		for (unsigned int j = i + 1; j <= ARRAY_SIZE; j++)
Здравствуйте, при i = 0, j = 1...5
при i = 1, j = 2...5
при i = 2, j = 3 4 5
при i = 3, j = 4 5
при i = 4, j = 5
i не будет равно 5 никогда, т.к. знак меньше
j не превысит 5, т.к. знак меньше-равно

2024-12-18 08:35 UTC, czertyaka commented
Задание принято

2024-12-18 08:35 UTC, closed without merging