Артюшин Артём Александрович, ДЗ по Cpp №3
czertyaka/CppDevCourse-hw3 pull request #29
Opened 2024-12-06 13:59 UTC by A1r3t0

two_sum

2024-12-06 16:08 UTC, A1r3t0 commented on src/two-sum.cpp
> +            index0 = std::min(map[complement], i);
при сборке у меня ругалось на эту строку, когда организовывал цикл через 
for (int i = 0; i < ARRAY_SIZE; ++i)
я правильно понимаю, что методы min и max должны принимать только одинаковые типы в качестве аргументов? можно ли как-то организовать функции, используя в цикле for не std::size_t i, а int i? если да, то это реализуется приведением типа int в функциях min и max аргумента i к std::size_t? или есть другой способ?

2024-12-06 16:12 UTC, A1r3t0 commented on src/two-sum.cpp
> +            index0 = std::min(map[complement], i);
имею в виду, что в функции min и max в качестве первого аргумента передается map[complement], map объявлен выше (<int, std::size_t>), он выдает в качестве значения по ключу тип std::size_t, соответственно i должно тоже передавать обязательно тип std::size_t?

2024-12-08 12:12 UTC, czertyaka requested changes

2024-12-08 12:12 UTC, czertyaka commented on .DS_Store
В пулл-реквесте не должно быть иных изменений, кроме добавления src/two-sum.cpp

2024-12-08 12:12 UTC, czertyaka commented on src/two-sum.cpp
> +            index0 = std::min(map[complement], i);
> можно ли как-то организовать функции, используя в цикле for не std::size_t i, а int i

Можно, но на мой взгляд, беззнаковый арифметический тип подходит лучше. А зачем использовать `int` для счетчика в цикле?
 
> если да, то это реализуется приведением типа int в функциях min и max аргумента i к std::size_t

Да, но есть риск сужающего приведения. В нашем случае такого не будет, но в общем случае текущее решение лучше.

2024-12-14 12:57 UTC, A1r3t0 commented on .DS_Store
Убрал остальные файлы, оставил только добавление two-sum.cpp в директории /src

2024-12-15 18:46 UTC, czertyaka commented
Задание принято

2024-12-15 18:46 UTC, closed without merging